FROM nginx:1.13-alpine
MAINTAINER Shijiang Wei<mountkin@gmail.com>

RUN apk update && \
  apk add curl && \
  curl -L -o /bin/confd https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64 && \
  chmod +x /bin/confd && \
  rm -fr /var/lib/apt/lists/*

RUN rm /etc/nginx/conf.d/default.conf
ADD init/init /init
ADD tpls /tpls
ADD csphere-services.json /etc/

ENTRYPOINT ["/init"]
EXPOSE 80 443
